
export const GET_ALL_COURSES_LOADING = 'GET_ALL_COURSES_LOADING';
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS';
export const GET_ALL_COURSES_ERROR = 'GET_ALL_COURSES_ERROR';

export const GET_COURSE_BY_SLUG_LOADING = 'GET_COURSE_BY_ID_LOADING';
export const GET_COURSE_BY_SLUG_SUCCESS = 'GET_COURSE_BY_ID_SUCCESS';
export const GET_COURSE_BY_SLUG_ERROR = 'GET_COURSE_BY_ID_ERROR';


// FOR ADMIN PANEL ONLY

export const ADD_COURSE_LOADING = 'ADD_COURSE_LOADING';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_ERROR = 'ADD_COURSE_ERROR';

export const UPDATE_COURSE_LOADING = 'UPDATE_COURSE_LOADING';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_ERROR = 'UPDATE_COURSE_ERROR';

export const DELETE_COURSE_LOADING = 'DELETE_COURSE_LOADING';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_ERROR = 'DELETE_COURSE_ERROR';
