
export const GET_ALL_COURSES_LOADING = 'GET_ALL_COURSES_LOADING';
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS';
export const GET_ALL_COURSES_ERROR = 'GET_ALL_COURSES_ERROR';

export const GET_COURSE_BY_SLUG_LOADING = 'GET_COURSE_BY_ID_LOADING';
export const GET_COURSE_BY_SLUG_SUCCESS = 'GET_COURSE_BY_ID_SUCCESS';
export const GET_COURSE_BY_SLUG_ERROR = 'GET_COURSE_BY_ID_ERROR';
