import React from "react";
import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import UserProfile from "../components/UserProfile";
import Footer from "../components/Footer";

const Profile = () => {
  return (
    <>
      <Head>
        <title>user-profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <UserProfile />
        <Footer />
      </Box>
    </>
  );
};

export default Profile;
